/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CheckBoxChangeEvent } from "./components/base/check-box/check-box";
import { Data } from "./models/data";
import { Group, GroupToggledEvent } from "./models/group";
import { Row } from "./models/row";
import { ToolbarButtonOptions, ToolbarOptions } from "./models/toolbar";
import { CustomTemplate, CustomTemplateFactoryReturnType } from "./models/customTemplate";
import { EditingOptions, EditionResultEvent, EditionValidationEvent } from "./models/edition";
import { SelectionEvent, SelectionOptions } from "./models/selection";
import { HeaderClickEvent, HeaderContextMenuEvent, ItemClickEvent, ItemContextMenuEvent, ItemDoubleClickEvent, ItemHooveringEvent } from "./models/click";
export { CheckBoxChangeEvent } from "./components/base/check-box/check-box";
export { Data } from "./models/data";
export { Group, GroupToggledEvent } from "./models/group";
export { Row } from "./models/row";
export { ToolbarButtonOptions, ToolbarOptions } from "./models/toolbar";
export { CustomTemplate, CustomTemplateFactoryReturnType } from "./models/customTemplate";
export { EditingOptions, EditionResultEvent, EditionValidationEvent } from "./models/edition";
export { SelectionEvent, SelectionOptions } from "./models/selection";
export { HeaderClickEvent, HeaderContextMenuEvent, ItemClickEvent, ItemContextMenuEvent, ItemDoubleClickEvent, ItemHooveringEvent } from "./models/click";
export namespace Components {
    interface CheckBox {
        "indeterminate"?: boolean;
        "isSelected": boolean;
    }
    interface DefaultCellEditTemplate {
        "data": Data;
        "focusInput": (options?: FocusOptions) => Promise<void>;
        "group"?: Group | undefined;
        "originalValue": any;
        "primaryKey": string;
        "row": Row;
        "selectAll": () => Promise<void>;
        "value": any;
    }
    interface DefaultCellTemplate {
        "data": Data;
        "group"?: Group | undefined;
        "originalValue": any;
        "primaryKey": string;
        "row": Row;
        "value": any;
    }
    interface GridToolbar {
        "center"?: ToolbarButtonOptions[];
        "left"?: ToolbarButtonOptions[];
        "right"?: ToolbarButtonOptions[];
        "toolbarTemplate"?: (props: CustomTemplate<ToolbarOptions>) => CustomTemplateFactoryReturnType;
    }
    interface IconChevronDown {
        "color"?: string;
        "size"?: string;
    }
    interface ItemCell {
        "data": Data;
        "group"?: Group | undefined;
        "isEditing": boolean;
        "originalValue": any;
        "primaryKey": string;
        "row": Row;
        "value": any;
    }
    interface TransposedGrid {
        "allowHeaderFiltering"?: boolean;
        "allowSorting"?: boolean;
        "cancelEdit": () => Promise<void>;
        "editing"?: EditingOptions;
        "fixedColumnWidth"?: string;
        "fixedGroups"?: Group[];
        "focusedRowPrimaryKeyValue"?: string;
        "groups"?: Group[];
        "height"?: string;
        "items": Data[];
        "maxPixelColumnWidth"?: number;
        "primaryKey"?: string;
        "redraw": () => Promise<void>;
        "rows"?: Row[];
        "saveEdit": () => Promise<void>;
        "selection"?: SelectionOptions;
        "striped": boolean;
        "tableClass"?: string;
        "toolbar"?: ToolbarOptions;
        "toolbarTemplate"?: (props: CustomTemplate<ToolbarOptions>) => CustomTemplateFactoryReturnType;
    }
}
export interface CheckBoxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCheckBoxElement;
}
export interface DefaultCellEditTemplateCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDefaultCellEditTemplateElement;
}
export interface ItemCellCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLItemCellElement;
}
export interface TransposedGridCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTransposedGridElement;
}
declare global {
    interface HTMLCheckBoxElementEventMap {
        "stateChange": CheckBoxChangeEvent;
    }
    interface HTMLCheckBoxElement extends Components.CheckBox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCheckBoxElementEventMap>(type: K, listener: (this: HTMLCheckBoxElement, ev: CheckBoxCustomEvent<HTMLCheckBoxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCheckBoxElementEventMap>(type: K, listener: (this: HTMLCheckBoxElement, ev: CheckBoxCustomEvent<HTMLCheckBoxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCheckBoxElement: {
        prototype: HTMLCheckBoxElement;
        new (): HTMLCheckBoxElement;
    };
    interface HTMLDefaultCellEditTemplateElementEventMap {
        "valueChange": any;
    }
    interface HTMLDefaultCellEditTemplateElement extends Components.DefaultCellEditTemplate, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDefaultCellEditTemplateElementEventMap>(type: K, listener: (this: HTMLDefaultCellEditTemplateElement, ev: DefaultCellEditTemplateCustomEvent<HTMLDefaultCellEditTemplateElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDefaultCellEditTemplateElementEventMap>(type: K, listener: (this: HTMLDefaultCellEditTemplateElement, ev: DefaultCellEditTemplateCustomEvent<HTMLDefaultCellEditTemplateElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDefaultCellEditTemplateElement: {
        prototype: HTMLDefaultCellEditTemplateElement;
        new (): HTMLDefaultCellEditTemplateElement;
    };
    interface HTMLDefaultCellTemplateElement extends Components.DefaultCellTemplate, HTMLStencilElement {
    }
    var HTMLDefaultCellTemplateElement: {
        prototype: HTMLDefaultCellTemplateElement;
        new (): HTMLDefaultCellTemplateElement;
    };
    interface HTMLGridToolbarElement extends Components.GridToolbar, HTMLStencilElement {
    }
    var HTMLGridToolbarElement: {
        prototype: HTMLGridToolbarElement;
        new (): HTMLGridToolbarElement;
    };
    interface HTMLIconChevronDownElement extends Components.IconChevronDown, HTMLStencilElement {
    }
    var HTMLIconChevronDownElement: {
        prototype: HTMLIconChevronDownElement;
        new (): HTMLIconChevronDownElement;
    };
    interface HTMLItemCellElementEventMap {
        "valueChange": any;
    }
    interface HTMLItemCellElement extends Components.ItemCell, HTMLStencilElement {
        addEventListener<K extends keyof HTMLItemCellElementEventMap>(type: K, listener: (this: HTMLItemCellElement, ev: ItemCellCustomEvent<HTMLItemCellElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLItemCellElementEventMap>(type: K, listener: (this: HTMLItemCellElement, ev: ItemCellCustomEvent<HTMLItemCellElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLItemCellElement: {
        prototype: HTMLItemCellElement;
        new (): HTMLItemCellElement;
    };
    interface HTMLTransposedGridElementEventMap {
        "itemClick": ItemClickEvent;
        "itemDoubleClick": ItemDoubleClickEvent;
        "itemHoovering": ItemHooveringEvent;
        "itemContextMenu": ItemContextMenuEvent;
        "headerClick": HeaderClickEvent;
        "headerContextMenu": HeaderContextMenuEvent;
        "editionStarted": EditionResultEvent;
        "editionValidation": EditionValidationEvent;
        "editionEnded": EditionResultEvent;
        "save": EditionResultEvent;
        "cancel": EditionResultEvent;
        "itemSelectionChange": SelectionEvent;
        "groupToggled": GroupToggledEvent;
        "contentRendered": void;
    }
    interface HTMLTransposedGridElement extends Components.TransposedGrid, HTMLStencilElement {
        addEventListener<K extends keyof HTMLTransposedGridElementEventMap>(type: K, listener: (this: HTMLTransposedGridElement, ev: TransposedGridCustomEvent<HTMLTransposedGridElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLTransposedGridElementEventMap>(type: K, listener: (this: HTMLTransposedGridElement, ev: TransposedGridCustomEvent<HTMLTransposedGridElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLTransposedGridElement: {
        prototype: HTMLTransposedGridElement;
        new (): HTMLTransposedGridElement;
    };
    interface HTMLElementTagNameMap {
        "check-box": HTMLCheckBoxElement;
        "default-cell-edit-template": HTMLDefaultCellEditTemplateElement;
        "default-cell-template": HTMLDefaultCellTemplateElement;
        "grid-toolbar": HTMLGridToolbarElement;
        "icon-chevron-down": HTMLIconChevronDownElement;
        "item-cell": HTMLItemCellElement;
        "transposed-grid": HTMLTransposedGridElement;
    }
}
declare namespace LocalJSX {
    interface CheckBox {
        "indeterminate"?: boolean;
        "isSelected"?: boolean;
        "onStateChange"?: (event: CheckBoxCustomEvent<CheckBoxChangeEvent>) => void;
    }
    interface DefaultCellEditTemplate {
        "data": Data;
        "group"?: Group | undefined;
        "onValueChange"?: (event: DefaultCellEditTemplateCustomEvent<any>) => void;
        "originalValue"?: any;
        "primaryKey": string;
        "row": Row;
        "value"?: any;
    }
    interface DefaultCellTemplate {
        "data": Data;
        "group"?: Group | undefined;
        "originalValue"?: any;
        "primaryKey": string;
        "row": Row;
        "value"?: any;
    }
    interface GridToolbar {
        "center"?: ToolbarButtonOptions[];
        "left"?: ToolbarButtonOptions[];
        "right"?: ToolbarButtonOptions[];
        "toolbarTemplate"?: (props: CustomTemplate<ToolbarOptions>) => CustomTemplateFactoryReturnType;
    }
    interface IconChevronDown {
        "color"?: string;
        "size"?: string;
    }
    interface ItemCell {
        "data": Data;
        "group"?: Group | undefined;
        "isEditing"?: boolean;
        "onValueChange"?: (event: ItemCellCustomEvent<any>) => void;
        "originalValue"?: any;
        "primaryKey": string;
        "row": Row;
        "value"?: any;
    }
    interface TransposedGrid {
        "allowHeaderFiltering"?: boolean;
        "allowSorting"?: boolean;
        "editing"?: EditingOptions;
        "fixedColumnWidth"?: string;
        "fixedGroups"?: Group[];
        "focusedRowPrimaryKeyValue"?: string;
        "groups"?: Group[];
        "height"?: string;
        "items"?: Data[];
        "maxPixelColumnWidth"?: number;
        "onCancel"?: (event: TransposedGridCustomEvent<EditionResultEvent>) => void;
        "onContentRendered"?: (event: TransposedGridCustomEvent<void>) => void;
        "onEditionEnded"?: (event: TransposedGridCustomEvent<EditionResultEvent>) => void;
        "onEditionStarted"?: (event: TransposedGridCustomEvent<EditionResultEvent>) => void;
        "onEditionValidation"?: (event: TransposedGridCustomEvent<EditionValidationEvent>) => void;
        "onGroupToggled"?: (event: TransposedGridCustomEvent<GroupToggledEvent>) => void;
        "onHeaderClick"?: (event: TransposedGridCustomEvent<HeaderClickEvent>) => void;
        "onHeaderContextMenu"?: (event: TransposedGridCustomEvent<HeaderContextMenuEvent>) => void;
        "onItemClick"?: (event: TransposedGridCustomEvent<ItemClickEvent>) => void;
        "onItemContextMenu"?: (event: TransposedGridCustomEvent<ItemContextMenuEvent>) => void;
        "onItemDoubleClick"?: (event: TransposedGridCustomEvent<ItemDoubleClickEvent>) => void;
        "onItemHoovering"?: (event: TransposedGridCustomEvent<ItemHooveringEvent>) => void;
        "onItemSelectionChange"?: (event: TransposedGridCustomEvent<SelectionEvent>) => void;
        "onSave"?: (event: TransposedGridCustomEvent<EditionResultEvent>) => void;
        "primaryKey"?: string;
        "rows"?: Row[];
        "selection"?: SelectionOptions;
        "striped"?: boolean;
        "tableClass"?: string;
        "toolbar"?: ToolbarOptions;
        "toolbarTemplate"?: (props: CustomTemplate<ToolbarOptions>) => CustomTemplateFactoryReturnType;
    }
    interface IntrinsicElements {
        "check-box": CheckBox;
        "default-cell-edit-template": DefaultCellEditTemplate;
        "default-cell-template": DefaultCellTemplate;
        "grid-toolbar": GridToolbar;
        "icon-chevron-down": IconChevronDown;
        "item-cell": ItemCell;
        "transposed-grid": TransposedGrid;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "check-box": LocalJSX.CheckBox & JSXBase.HTMLAttributes<HTMLCheckBoxElement>;
            "default-cell-edit-template": LocalJSX.DefaultCellEditTemplate & JSXBase.HTMLAttributes<HTMLDefaultCellEditTemplateElement>;
            "default-cell-template": LocalJSX.DefaultCellTemplate & JSXBase.HTMLAttributes<HTMLDefaultCellTemplateElement>;
            "grid-toolbar": LocalJSX.GridToolbar & JSXBase.HTMLAttributes<HTMLGridToolbarElement>;
            "icon-chevron-down": LocalJSX.IconChevronDown & JSXBase.HTMLAttributes<HTMLIconChevronDownElement>;
            "item-cell": LocalJSX.ItemCell & JSXBase.HTMLAttributes<HTMLItemCellElement>;
            "transposed-grid": LocalJSX.TransposedGrid & JSXBase.HTMLAttributes<HTMLTransposedGridElement>;
        }
    }
}
